export { CURRENT_SCHEMA_VERSION, SUPPORTED_TRIGGER_TYPES, OBSERVATION_ROLES, PLUGIN_STAGES, isSupportedTriggerType, isObservationRole } from "./contract/v4.js";
export { createAnimationPlugin } from "./domain/createAnimationPlugin.js";
export { ALL_PLUGINS, createPluginRegistry, registerPlugin, unregisterPlugin, resolvePluginForKey, resolvePluginInput, ensureLoaded, getInternalKeys, getOutputSerializers, pathPlugin, cssVarPlugin, imageSequencePlugin, fkPlugin } from "./domain/plugins.js";
export { buildTrackTween, buildTrackTweenSync } from "./usecases/BuildTrackTween.js";
export { composeTrackPatch, composePatch } from "./usecases/ComposeTrackPatch.js";
export { resolveTrack, resolveTrackKeyframes } from "./usecases/ResolveTrack.js";
export { mergePatches } from "./usecases/mergePatches.js";
export { Overlay } from "./usecases/Overlay.js";
export { Spawner } from "./usecases/Spawner.js";
export { Engine, engine } from "./engines/Engine.js";
export { Track, } from "./lib/Track.js";
export { Motion, TrackGroup } from "./lib/Motion.js";
export { createTrack } from "./lib/createTrack.js";
export * from "./validators/index.js";
