/**
 * Project-scoped ownership and staged visibility boundary.
 *
 * A candidate is invisible until commitCandidate succeeds. Membership and the
 * graph runtime are owned by the committed project, never by individual Motion
 * instances. Cross-motion and free-track behavior are explicit capabilities.
 */
export class ProjectRuntime {
  #active = null; #candidate = null; #instances = new Map(); #instanceMetadata = new Map(); #graphRuntime = null; #capabilities; #diagnostics = []; #disposed = false;
  constructor({ capabilities = {} } = {}) { this.#capabilities = Object.freeze({ crossMotion: capabilities.crossMotion === true, freeTracks: capabilities.freeTracks === true }); }
  get isDisposed() { return this.#disposed; } get isCommitted() { return this.#active !== null; } get project() { return this.#active?.project ?? null; } get projectId() { return this.#active?.project?.projectId ?? null; } get candidateProject() { return this.#candidate?.project ?? null; } get instanceCount() { return this.#instances.size; } get instances() { return new Map(this.#instances); } get membership() { return new Map(this.#active?.membership ?? []); } get candidateMembership() { return new Map(this.#candidate?.membership ?? []); } get graphRuntime() { return this.#graphRuntime; } get capabilities() { return { ...this.#capabilities }; } get diagnostics() { return this.#diagnostics.map((diagnostic) => ({ ...diagnostic })); } get pendingReferences() { return new Map(this.#active?.pending ?? []); } get candidatePendingReferences() { return new Map(this.#candidate?.pending ?? []); } get references() { return new Map(this.#active?.references ?? []); }
  get qualifiedMembershipOrder() { return [...this.membership.keys()].sort((a, b) => { const aFree = a.startsWith('~/'); const bFree = b.startsWith('~/'); if (aFree !== bFree) return aFree ? 1 : -1; return a.localeCompare(b); }); }
  assertCapability(capability) { if (capability !== 'crossMotion' && capability !== 'freeTracks') throw new Error(`Unknown ProjectRuntime capability '${capability}'.`); if (!this.#capabilities[capability]) throw new Error(`ProjectRuntime capability '${capability}' is disabled.`); return true; }
  recordDiagnostic(code, details = {}) { const diagnostic = Object.freeze({ code, ...details }); this.#diagnostics.push(diagnostic); return diagnostic; }
  beginCandidate(project) { this.#assertAlive(); if (!project || typeof project !== 'object') throw new TypeError('ProjectRuntime candidate must be an object.'); if (this.#candidate) throw new Error('ProjectRuntime already has a candidate project.'); const candidate = { project, instances: new Map(), metadata: new Map(), membership: new Map(), pending: new Map(), references: new Map(), resources: new Set() }; this.#candidate = candidate; return candidate; }
  registerCandidate(candidate, id, value, metadata = {}) { this.#assertCandidate(candidate); if (typeof id !== 'string' || id.length === 0) throw new TypeError('ProjectRuntime candidate id must be a non-empty string.'); if (candidate.membership.has(id)) throw new Error(`ProjectRuntime candidate already registers '${id}'.`); candidate.membership.set(id, { value, metadata: { ...metadata } }); candidate.pending.delete(id); if (value && typeof value.destroy === 'function') candidate.resources.add(value); return value; }
  registerPendingReference(candidate, id, metadata = {}) { this.#assertCandidate(candidate); if (typeof id !== 'string' || id.length === 0) throw new TypeError('ProjectRuntime pending reference id must be a non-empty string.'); if (candidate.membership.has(id)) throw new Error(`ProjectRuntime reference '${id}' is already resolved.`); candidate.pending.set(id, { ...metadata, id, status: 'pending' }); return candidate.pending.get(id); }
  registerReference(id, { sourceId, targetId, role = 'output', input } = {}) { this.#assertAlive(); this.assertCapability('crossMotion'); if (!this.#active) throw new Error('ProjectRuntime has no committed project.'); if (typeof id !== 'string' || !id.length || typeof sourceId !== 'string' || !sourceId.length || typeof targetId !== 'string' || !targetId.length) throw new TypeError('ProjectRuntime reference requires id, sourceId, and targetId.'); if (this.#active.references.has(id)) throw new Error(`ProjectRuntime reference '${id}' already exists.`); const status = this.#instances.has(sourceId) ? 'ready' : 'pending'; const reference = Object.freeze({ id, sourceId, targetId, role, input, status }); this.#active.references.set(id, reference); if (status === 'pending') this.#active.pending.set(id, { id, source: sourceId, target: targetId, role, input, status }); return reference; }
  removeReference(id, { diagnostic = true } = {}) { this.#assertAlive(); if (!this.#active?.references.has(id)) return false; const reference = this.#active.references.get(id); this.#active.references.delete(id); this.#active.pending.delete(id); if (diagnostic) this.recordDiagnostic('REFERENCE_REMOVED', { referenceId: id, sourceId: reference.sourceId, targetId: reference.targetId }); return true; }
  commitCandidate(candidate) { this.#assertCandidate(candidate); const previous = this.#active; this.#active = { project: candidate.project, instances: new Map(candidate.instances), metadata: new Map(candidate.metadata), membership: new Map(candidate.membership), pending: new Map(candidate.pending), references: new Map(candidate.references) }; this.#candidate = null; this.#instances.clear(); this.#instanceMetadata.clear(); candidate.resources.clear(); return previous?.project ?? null; }
  abortCandidate(candidate, { destroy = true } = {}) { if (!candidate || this.#candidate !== candidate) return false; this.#candidate = null; if (destroy) { for (const value of candidate.instances.values()) value?.destroy?.(); for (const value of candidate.resources) value?.destroy?.(); } candidate.instances.clear(); candidate.metadata.clear(); candidate.membership.clear(); candidate.pending.clear(); candidate.references.clear(); candidate.resources.clear(); return true; }
  resolvePendingReference(id, value, metadata = {}) { this.#assertAlive(); if (!this.#active) throw new Error('ProjectRuntime has no committed project.'); if (!this.#active.pending.has(id)) throw new Error(`ProjectRuntime has no pending reference '${id}'.`); const pending = this.#active.pending.get(id); this.#active.pending.delete(id); this.#active.membership.set(id, { value, metadata: { ...pending, ...metadata, status: 'resolved' } }); return value; }
  canPublish(id) { return Boolean(this.#active?.membership.has(id) && !this.#active?.pending.has(id)); }
  sampleProgress(id) { this.#assertAlive(); const instance = this.#instances.get(id); if (!instance) throw new Error(`ProjectRuntime has no mounted instance '${id}'.`); if (typeof instance.progress !== 'function') throw new TypeError(`ProjectRuntime instance '${id}' cannot report progress.`); return instance.progress(); }
  sampleQualifiedProgress(qualifiedId) { const membership = this.#active?.membership?.get(qualifiedId); if (!membership) { if (this.#active?.pending?.has(qualifiedId)) return { status: 'pending', qualifiedId }; throw new Error(`ProjectRuntime has no qualified member '${qualifiedId}'.`); } const instanceId = membership.metadata?.instanceId ?? qualifiedId; const instance = this.#instances.get(instanceId); if (!instance) return { status: 'pending', qualifiedId }; return { status: 'ready', qualifiedId, progress: this.sampleProgress(instanceId) }; }
  attachGraphRuntime(runtime) { this.#assertAlive(); if (!this.#active) throw new Error('ProjectRuntime has no committed project.'); if (!runtime || typeof runtime.flush !== 'function' || typeof runtime.dispose !== 'function') throw new TypeError('ProjectRuntime graph runtime must support flush() and dispose().'); if (this.#graphRuntime && this.#graphRuntime !== runtime) this.#graphRuntime.dispose(); this.#graphRuntime = runtime; return runtime; }
  flush() { return this.#graphRuntime?.flush?.() ?? 0; } getPatch(nodeId) { return this.#graphRuntime?.getPatch?.(nodeId) ?? null; } subscribe(nodeId, callback) { if (!this.#graphRuntime) throw new Error('ProjectRuntime has no graph runtime.'); return this.#graphRuntime.subscribe(nodeId, callback); }
  registerInstance(id, value, metadata = {}) { this.#assertAlive(); if (!this.#active) throw new Error('ProjectRuntime has no committed project.'); if (typeof id !== 'string' || id.length === 0) throw new TypeError('ProjectRuntime instance id must be a non-empty string.'); if (this.#instances.has(id)) throw new Error(`ProjectRuntime already owns instance '${id}'.`); this.#instances.set(id, value); this.#instanceMetadata.set(id, { ...metadata }); for (const [referenceId, reference] of this.#active.references) if (reference.sourceId === id && reference.status === 'pending') { const ready = Object.freeze({ ...reference, status: 'ready' }); this.#active.references.set(referenceId, ready); this.#active.pending.delete(referenceId); } return value; }
  unregisterInstance(id, { destroy = true } = {}) { if (!this.#instances.has(id)) return false; const value = this.#instances.get(id); this.#instances.delete(id); this.#instanceMetadata.delete(id); const removedReferences = [...(this.#active?.references ?? [])].filter(([, reference]) => reference.sourceId === id).map(([referenceId]) => referenceId); for (const referenceId of removedReferences) this.removeReference(referenceId, { diagnostic: false }); const removedPending = [...(this.#active?.pending ?? [])].filter(([, reference]) => reference.source === id).map(([referenceId]) => referenceId); for (const referenceId of removedPending) this.#active.pending.delete(referenceId); this.recordDiagnostic('SOURCE_UNMOUNTED', { sourceId: id, removedReferences: [...new Set([...removedReferences, ...removedPending])] }); if (destroy) value?.destroy?.(); return true; }
  lookupInstance(id) { return this.#instances.get(id) ?? null; } getInstanceMetadata(id) { const metadata = this.#instanceMetadata.get(id); return metadata ? { ...metadata } : null; } getProjectLookup(id) { return this.#active?.membership?.get(id)?.value ?? null; }
  dispose() { if (this.#disposed) return; this.#disposed = true; this.abortCandidate(this.#candidate); this.#graphRuntime?.dispose?.(); this.#graphRuntime = null; for (const value of this.#instances.values()) value?.destroy?.(); this.#instances.clear(); this.#instanceMetadata.clear(); this.#active = null; }
  #assertCandidate(candidate) { this.#assertAlive(); if (!candidate || this.#candidate !== candidate) throw new Error('ProjectRuntime candidate is not active.'); } #assertAlive() { if (this.#disposed) throw new Error('ProjectRuntime is disposed.'); }
}
