import { describe, expect, it } from 'vitest';
import { ProjectRuntime } from '../ProjectRuntime.js';
const project = (projectId) => ({ projectId });
describe('ProjectRuntime staged visibility', () => {
  it('samples a mounted source at its current progress without controlling it', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('sample')); runtime.registerCandidate(candidate, 'right/bone', { id: 'bone' }, { instanceId: 'motion#1' }); runtime.commitCandidate(candidate); let progress = 0.42; let calls = 0; let controlled = false; runtime.registerInstance('motion#1', { progress: () => { calls += 1; return progress; }, seek: () => { controlled = true; } }); expect(runtime.sampleQualifiedProgress('right/bone')).toEqual({ status: 'ready', qualifiedId: 'right/bone', progress: 0.42 }); expect(calls).toBe(1); expect(controlled).toBe(false); });
  it('returns pending instead of publishing when a qualified source is not mounted', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('pending')); runtime.registerPendingReference(candidate, 'right/bone'); runtime.commitCandidate(candidate); expect(runtime.sampleQualifiedProgress('right/bone')).toEqual({ status: 'pending', qualifiedId: 'right/bone' }); });
  it('keeps unresolved references pending and unpublished', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('pending')); runtime.registerPendingReference(candidate, 'right/bone', { source: 'right' }); runtime.commitCandidate(candidate); expect(runtime.pendingReferences.get('right/bone')).toMatchObject({ status: 'pending', source: 'right' }); expect(runtime.canPublish('right/bone')).toBe(false); });
  it('records source-unmount diagnostics and removes dependent pending references', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('unmount')); runtime.registerPendingReference(candidate, 'left/root', { source: 'right/bone' }); runtime.commitCandidate(candidate); runtime.registerInstance('right/bone', { destroy() {} }); expect(runtime.unregisterInstance('right/bone')).toBe(true); expect(runtime.diagnostics[0]).toMatchObject({ code: 'SOURCE_UNMOUNTED', sourceId: 'right/bone', removedReferences: ['left/root'] }); });
  it('keeps capability gates disabled by default', () => { const runtime = new ProjectRuntime(); expect(runtime.capabilities).toEqual({ crossMotion: false, freeTracks: false }); expect(() => runtime.assertCapability('crossMotion')).toThrow(/disabled/); });
  it('exposes stable canonical membership order', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('order')); runtime.registerCandidate(candidate, '~/z', {}); runtime.registerCandidate(candidate, 'right/bone', {}); runtime.registerCandidate(candidate, 'left/bone', {}); runtime.commitCandidate(candidate); expect(runtime.qualifiedMembershipOrder).toEqual(['left/bone', 'right/bone', '~/z']); });
  it('owns one graph runtime and disposes replacement and final graph exactly once', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('active')); runtime.commitCandidate(candidate); const first = { flush: () => 3, dispose: () => { first.disposed = (first.disposed ?? 0) + 1; }, getPatch: () => null, subscribe: () => () => {} }; const second = { flush: () => 4, dispose: () => { second.disposed = (second.disposed ?? 0) + 1; }, getPatch: () => null, subscribe: () => () => {} }; runtime.attachGraphRuntime(first); runtime.attachGraphRuntime(second); expect(first.disposed).toBe(1); runtime.dispose(); expect(second.disposed).toBe(1); });
});
