import { describe, expect, it } from 'vitest';
import { ProjectRuntime } from '../ProjectRuntime.js';
import { ScopedObservationAdapter } from '../../usecases/ScopedObservationAdapter.js';
import { StandaloneObservationAdapter } from '../../usecases/StandaloneObservationAdapter.js';
const project = (projectId) => ({ projectId });
describe('ProjectRuntime reference validation', () => {
  it('keeps cross-motion references disabled by default', () => { const runtime = new ProjectRuntime(); const candidate = runtime.beginCandidate(project('gated')); runtime.commitCandidate(candidate); expect(() => runtime.registerReference('r', { sourceId: 'right/bone', targetId: 'left/root' })).toThrow(/disabled/); });
  it('rejects malformed namespaces, roles, self-edges, and duplicate IDs', () => { const runtime = new ProjectRuntime({ capabilities: { crossMotion: true } }); const candidate = runtime.beginCandidate(project('validate')); runtime.commitCandidate(candidate); expect(() => runtime.registerReference('right/r', { sourceId: 'a', targetId: 'b' })).toThrow(/namespace/); expect(() => runtime.registerReference('r', { sourceId: 'a', targetId: 'a' })).toThrow(/itself/); expect(() => runtime.registerReference('r', { sourceId: 'a', targetId: 'b', role: 'wat' })).toThrow(/role/); runtime.registerReference('r', { sourceId: 'a', targetId: 'b' }); expect(() => runtime.registerReference('r', { sourceId: 'a', targetId: 'b' })).toThrow(/already exists/); });
  it('keeps free-track references explicit and separately gated', () => { const runtime = new ProjectRuntime({ capabilities: { crossMotion: true } }); const candidate = runtime.beginCandidate(project('free')); runtime.commitCandidate(candidate); runtime.registerReference('r', { sourceId: '~/free', targetId: 'left/root' }); expect(runtime.references.get('r').status).toBe('pending'); });
  it('holds missing sources pending then resolves on explicit mount', () => { const runtime = new ProjectRuntime({ capabilities: { crossMotion: true } }); const candidate = runtime.beginCandidate(project('pending')); runtime.commitCandidate(candidate); runtime.registerReference('r', { sourceId: 'right/bone', targetId: 'left/root' }); expect(runtime.pendingReferences.has('r')).toBe(true); runtime.registerInstance('right/bone', { progress: () => 0.6 }); expect(runtime.references.get('r').status).toBe('ready'); });
  it('samples ready sources and removes references on unmount', () => { const runtime = new ProjectRuntime({ capabilities: { crossMotion: true } }); const candidate = runtime.beginCandidate(project('lifecycle')); runtime.commitCandidate(candidate); runtime.registerInstance('right/bone', { progress: () => 0.6, destroy() {} }); runtime.registerReference('r', { sourceId: 'right/bone', targetId: 'left/root' }); expect(runtime.sampleReferenceProgress('r').progress).toBe(0.6); runtime.unregisterInstance('right/bone'); expect(runtime.references.has('r')).toBe(false); runtime.registerInstance('right/bone', { progress: () => 0.3 }); expect(runtime.references.has('r')).toBe(false); });
  it('supports explicit reattachment and retains default-off free tracks', () => { const runtime = new ProjectRuntime({ capabilities: { crossMotion: true } }); const candidate = runtime.beginCandidate(project('reattach')); runtime.commitCandidate(candidate); runtime.registerInstance('right/bone', { progress: () => 0.2 }); runtime.registerReference('r', { sourceId: 'right/bone', targetId: 'left/root' }); runtime.removeReference('r'); expect(runtime.registerReference('r', { sourceId: 'right/bone', targetId: 'left/root' }).status).toBe('ready'); expect(() => runtime.registerFreeTrack('~/floater', {})).toThrow(/disabled/); });
  it('owns one standalone adapter for the runtime lifetime', () => { const runtime = new ProjectRuntime(); const adapter = runtime.standaloneObservationAdapter; expect(adapter).toBe(runtime.standaloneObservationAdapter); expect(adapter.isDestroyed).toBe(false); runtime.dispose(); expect(adapter.isDestroyed).toBe(true); expect(() => runtime.standaloneObservationAdapter).toThrow(/disposed/); });
  it('keeps compatibility ownership as the default', () => { const runtime = new ProjectRuntime(); expect(runtime.observationOwnership).toBe('compatibility'); expect(runtime.standaloneObservationAdapter).toBeInstanceOf(StandaloneObservationAdapter); runtime.dispose(); });
  it('allows scoped ownership only when explicitly requested', () => { const runtime = new ProjectRuntime({ observationOwnership: 'scoped' }); expect(runtime.observationOwnership).toBe('scoped'); expect(runtime.standaloneObservationAdapter).toBeInstanceOf(ScopedObservationAdapter); runtime.dispose(); });
  it('rejects unknown ownership modes before creating a runtime', () => { expect(() => new ProjectRuntime({ observationOwnership: 'global' })).toThrow(/compatibility.*scoped/i); });
});
