import { composePatch } from "../usecases/ComposeTrackPatch.js";
import { COMPOSING } from "../usecases/composeContext.js";
import { mergePatches } from "../usecases/mergePatches.js";
import { observationEdgeKey } from "../usecases/observationEdge.js";
import { StandaloneObservationAdapter } from "../usecases/StandaloneObservationAdapter.js";
import { defaultGaplessLayoutDelegate } from "./GaplessLayoutDelegate.js";
import { eventBus as defaultEventBus } from "./eventBus.js";
import { logger } from "./logger.js";
const clamp01=val=>Math.max(0,Math.min(1,Number(val)||0));
export class Track {
 #id;#mode;#interpolationTimeline;#proxyState;#plugins;#resolvedTrack;#eventBus;#host=null;#parent=null;#children=new Map();#subscribers=new Set();#lifecycleSubscribers=new Set();#destroySubscribers=new Set();#currentOffset=0;#staggerOffset=0;#layoutDelegate;#observed=new Map();#observers=new Map();#graphGuard=null;#observationComposer=null;#standaloneObservationAdapter;#groupHost=null;#destroyed=false;
 constructor({id,mode="standalone",interpolationTimeline,proxyState,plugins,resolvedTrack,layoutDelegate,eventBus=defaultEventBus,observationAdapter=null}){this.#id=id;this.#mode=mode==="authored-graph"?"authored-graph":"standalone";this.#interpolationTimeline=interpolationTimeline;this.#proxyState=proxyState;this.#plugins=plugins;this.#resolvedTrack=resolvedTrack;this.#layoutDelegate=layoutDelegate??defaultGaplessLayoutDelegate;this.#eventBus=eventBus;this.#standaloneObservationAdapter=this.#mode==="standalone"?(observationAdapter??new StandaloneObservationAdapter()):null;this.#standaloneObservationAdapter?.register(this)}
 get id(){return this.#id}get mode(){return this.#mode}get currentOffset(){return this.#currentOffset}get parent(){return this.#parent}get duration(){return this.#interpolationTimeline?.duration()??0}get isDestroyed(){return this.#destroyed}
 progress(p){if(p===undefined)return this.#interpolationTimeline?.progress()??0;if(this.#destroyed)return;this.#interpolationTimeline?.progress(clamp01(p));this.#notify();this.#invalidate("progress")}
 getSnapshot(){this.#assertAlive();const{_gsap,...rest}=this.#proxyState||{};return{...rest,progress:this.#interpolationTimeline?.progress()??0}}
 composeLocal(raw){this.#assertAlive();return composePatch(this.#plugins,raw??this.getSnapshot(),this.#resolvedTrack,`track "${this.#id}"`)}
 compose(raw,ctx){this.#assertAlive();if(this.#observationComposer)return this.#observationComposer(raw,ctx);if(this.#standaloneObservationAdapter)return this.#standaloneObservationAdapter.compose(this,raw,ctx);ctx??=new Map();const cached=ctx.get(this.#id);if(cached===COMPOSING)return this.composeLocal(raw);if(cached!==undefined)return cached;ctx.set(this.#id,COMPOSING);let source=raw??this.getSnapshot();for(const{source:s,mapFn,role}of this.#observed.values()){if(role!=="input"||!mapFn)continue;const c=mapFn(s.compose(undefined,ctx));if(c)source={...source,...c}}let patch=this.composeLocal(source);for(const{source:s,mapFn,role}of this.#observed.values()){if(role!=="output"||!mapFn)continue;const c=mapFn(s.compose(undefined,ctx));if(c)patch=mergePatches(patch,c)}ctx.set(this.#id,patch);return patch}
 setObserved(track,mapFn,opts={}){if(!track){if(this.#standaloneObservationAdapter)this.#standaloneObservationAdapter.clearObserved(this);else this.#clearObserved();this.#invalidate("observation");return}if(track===this)throw new Error(`Track "${this.#id}" cannot observe itself.`);if(track.isDestroyed)throw new Error(`Track "${track.id}" is destroyed.`);const role=opts.role??"output",input=role==="input"?opts.target:undefined;this.#graphGuard?.(this,track,{role,input});const key=observationEdgeKey(track.id,role,input),previous=this.#observed.get(key);if(this.#standaloneObservationAdapter){this.#standaloneObservationAdapter.setObserved(this,track,mapFn,opts);this.#observed.set(key,{source:track,mapFn:mapFn??null,role,input});track._addObserver(this,key);this.#emitLifecycle({type:previous?"edge-replaced":"edge-added",track:this,source:track,edge:{source:track.id,target:this.#id,role,input}});this.#invalidate("observation");return}if(previous)previous.source._removeObserver(this,key);this.#observed.set(key,{source:track,mapFn:mapFn??null,role,input});track._addObserver(this,key);this.#emitLifecycle({type:previous?"edge-replaced":"edge-added",track:this,source:track,edge:{source:track.id,target:this.#id,role,input}});this.#invalidate("observation")}
 removeObserved(track,opts={}){if(!track)return;if(this.#standaloneObservationAdapter)this.#standaloneObservationAdapter.removeObserved(this,track,opts);const keys=[...this.#observed.entries()].filter(([,e])=>e.source===track&&(opts.role===undefined||e.role===opts.role)&&(opts.role!=="input"||opts.target===undefined||e.input===opts.target)).map(([k])=>k);for(const k of keys)this.#removeObservedKey(k);if(keys.length)this.#invalidate("observation")}
 replaceObserved(oldSource,newSource,mapFn,opts={}){if(!oldSource||!newSource)throw new TypeError("replaceObserved requires old and new source tracks.");if(newSource===this)throw new Error(`Track "${this.#id}" cannot observe itself.`);if(oldSource===newSource)throw new Error("replaceObserved requires two different source tracks.");this.#graphGuard?.(this,newSource,opts);const replaced=[...this.#observed.entries()].filter(([,e])=>e.source===oldSource&&(opts.role===undefined||e.role===opts.role));if(this.#standaloneObservationAdapter){if(!replaced.length)throw new Error(`Track "${this.#id}" does not observe "${oldSource.id}".`);for(const[,e]of replaced){this.#standaloneObservationAdapter.removeObserved(this,oldSource,{role:e.role,target:e.input});this.#emitLifecycle({type:"edge-removed",track:this,source:oldSource,edge:{source:oldSource.id,target:this.#id,role:e.role,input:e.input}})}this.#standaloneObservationAdapter.replaceObserved(this,oldSource,newSource,mapFn,opts);for(const[,e]of replaced){const role=e.role,input=role==="input"?(opts.target??e.input):undefined;const key=observationEdgeKey(newSource.id,role,input);this.#observed.delete(observationEdgeKey(oldSource.id,role,e.input));this.#observed.set(key,{source:newSource,mapFn:mapFn??e.mapFn,role,input});oldSource._removeObserver(this,observationEdgeKey(oldSource.id,role,e.input));newSource._addObserver(this,key);this.#emitLifecycle({type:"edge-added",track:this,source:newSource,edge:{source:newSource.id,target:this.#id,role,input}})}this.#invalidate("observation");return}if(!replaced.length)throw new Error(`Track "${this.#id}" does not observe "${oldSource.id}".`);for(const[k,e]of replaced)this.#removeObservedKey(k);this.setObserved(newSource,mapFn??e.mapFn,{role:e.role,target:e.input})}
 get observedSources(){return this.#standaloneObservationAdapter?this.#standaloneObservationAdapter.state.getSources(this.#id).map(id=>this.#standaloneObservationAdapter.tracks.get(id)).filter(Boolean):[...new Set([...this.#observed.values()].map(e=>e.source))]}
 get observedEdges(){return this.#standaloneObservationAdapter?this.#standaloneObservationAdapter.state.getEdges(this.#id).map(({source,mapFn,role,input})=>({source,mapFn,role,input,target:this.#id})):[...this.#observed.values()].map(({source,mapFn,role,input})=>({source,mapFn,role,input,target:this.#id}))}
 get observerCount(){return this.#observers.size}get observerIds(){return[...this.#observers.keys()].map(o=>o.id)}
 onLifecycle(cb){if(typeof cb!=="function")throw new TypeError("Track lifecycle callback must be a function.");this.#lifecycleSubscribers.add(cb);return()=>this.#lifecycleSubscribers.delete(cb)}onSourceDestroyed(cb){if(typeof cb!=="function")throw new TypeError("Track destroy callback must be a function.");this.#destroySubscribers.add(cb);return()=>this.#destroySubscribers.delete(cb)}subscribe(cb){this.#subscribers.add(cb);cb(this.getSnapshot());return()=>this.#subscribers.delete(cb)}
 _setGraphGuard(g){this.#graphGuard=g??null}_setObservationComposer(c){this.#observationComposer=typeof c==="function"?c:null}_addObserver(o,k){const s=this.#observers.get(o)??new Set();s.add(k);this.#observers.set(o,s)}_removeObserver(o,k){const s=this.#observers.get(o);if(!s)return;s.delete(k);if(!s.size)this.#observers.delete(o)}
 #notify(){const s=this.getSnapshot();for(const cb of this.#subscribers)cb(s)}#emitLifecycle(e){if(this.#destroyed&&e.type!=="destroyed")return;for(const cb of[...this.#lifecycleSubscribers])cb(e)}#invalidate(r){this.#emitLifecycle({type:"invalidated",track:this,reason:r})}#assertAlive(){if(this.#destroyed)throw new Error(`Track "${this.#id}" is destroyed.`)}
 #removeObservedKey(k){const e=this.#observed.get(k);if(!e)return;this.#observed.delete(k);if(this.#standaloneObservationAdapter)this.#standaloneObservationAdapter.removeObserved(this,e.source,{role:e.role,target:e.input});e.source._removeObserver(this,k);this.#emitLifecycle({type:"edge-removed",track:this,source:e.source,edge:{source:e.source.id,target:this.#id,role:e.role,input:e.input}})}#clearObserved(){for(const k of[...this.#observed.keys()])this.#removeObservedKey(k)}#detachObservationEdges(){for(const[o,keys]of[...this.#observers])for(const k of keys)o.#removeObservedKey(k);this.#observers.clear();this.#clearObserved()}
 _mount(h){if(this.#destroyed)throw new Error(`Track "${this.#id}" is destroyed.`);if(this.#host)throw new Error(`Track "${this.#id}" already mounted`);this.#host=h}_unmount(){this.#host=null}get isMounted(){return this.#host!==null}get childCount(){return this.#children.size}getChild(id){return this.#children.get(id)??null}
 addChild(child,opts={}){if(this.#destroyed)throw new Error(`Track "${this.#id}" is destroyed.`);if(child.#parent)throw new Error(`Track "${child.id}" is already a child of "${child.#parent.id}"`);if(this.#children.has(child.id))throw new Error(`Track "${this.#id}" already has a child with id "${child.id}".`);child.#parent=this;const stagger=opts.stagger??0;child.#staggerOffset=stagger;child.#currentOffset=this.#layoutDelegate.computeSpawnOffset([...this.#children.values()],{stagger});this.#children.set(child.id,child);if(this.#host)this.#host._mountChild(child,child.#currentOffset);this.#eventBus.emit("child:spawned",{id:child.id,parentId:this.#id});this.#invalidate("children")}
 removeChild(id){const child=this.#children.get(id);if(!child)return;const siblings=[...this.#children.values()];this.#children.delete(id);child.#parent=null;child.#detachObservationEdges();if(this.#host)this.#host._unmountChild(child);for(const t of this.#layoutDelegate.computeReflow(siblings,child,{})){t.child.#currentOffset=t.offset;if(this.#host)this.#host._reflowChild(t.child,t.offset)}child.#emitLifecycle({type:"detached",track:child,parent:this});this.#eventBus.emit("child:removing",{id:child.id,parentId:this.#id})}
 _attachGroupHost(g){if(this.#groupHost)throw new Error(`Track "${this.#id}" is already a group host.`);this.#groupHost=g}play(){this.#groupHost?.timeline.play()}pause(){this.#groupHost?.timeline.pause()}seek(p){if(!this.#groupHost)return this.progress(p);if(p===undefined)return this.#groupHost.timeline.progress();this.#groupHost.timeline.progress(clamp01(p))}reverse(){this.#groupHost?.timeline.reverse()}
 destroy(){if(this.#destroyed)return;const observerIds=this.observerIds;this.#detachObservationEdges();this.#destroyed=true;this.#observationComposer=null;this.#standaloneObservationAdapter?.unregister(this.#id);for(const child of this.#children.values())child.destroy();this.#children.clear();this.#parent=null;this.#host=null;this.#subscribers.clear();this.#graphGuard=null;const event={id:this.#id,observerIds};for(const cb of[...this.#destroySubscribers])cb(event);this.#emitLifecycle({type:"destroyed",track:this,observerIds:event.observerIds});this.#destroySubscribers.clear();this.#lifecycleSubscribers.clear();if(this.#groupHost){this.#groupHost.group.destroy();this.#groupHost.timeline.kill();this.#groupHost=null}try{this.#interpolationTimeline?.kill()}catch(e){logger.warn(`track "${this.#id}", failed to kill interpolation timeline during destroy()`,e)}}
}
