import { gsap, registerScrollTrigger } from "../adapters/gsapPlatform.js";
function clamp01(value) { return Math.max(0, Math.min(1, Number(value) || 0)); }
export class AutonomousTimelineControls { #timeline; constructor(timeline) { this.#timeline = timeline; } play() { this.#timeline.play(); } pause() { this.#timeline.pause(); } seek(p) { this.#timeline.progress(clamp01(p)); } reverse() { this.#timeline.reverse(); } onComplete(cb) { this.#timeline.eventCallback("onComplete", cb); } }
export function isScrubbedScrollConfig(config = {}) { return config.scrub === true || typeof config.scrub === "number"; }
export class ScrollTriggerDelegate { #config; #controls; #timeline; constructor(config = {}) { this.#config = config; } buildTimelineVars() { const c = this.#config; const trigger = c.trigger; const scrollTrigger = { start: c.start, end: c.end, scrub: c.scrub, pin: c.pin === true ? trigger : c.pin, pinSpacing: c.pinSpacing, toggleActions: c.toggleActions }; if (trigger) scrollTrigger.trigger = trigger; if (c.endTrigger) scrollTrigger.endTrigger = c.endTrigger; const vars = { scrollTrigger }; if (!isScrubbedScrollConfig(c)) { vars.repeat = c.repeat ?? 0; vars.yoyo = !!c.yoyo; vars.repeatDelay = c.repeatDelay ?? 0; if (typeof c.delay === "number") vars.delay = c.delay; } return vars; } build() { registerScrollTrigger(); this.#timeline = gsap.timeline(this.buildTimelineVars()); this.#controls = new AutonomousTimelineControls(this.#timeline); return this.#timeline; } play() { this.#controls?.play(); } pause() { this.#controls?.pause(); } seek(p) { this.#controls?.seek(p); } reverse() { this.#controls?.reverse(); } onComplete(cb) { this.#controls?.onComplete(cb); } destroy() { this.#timeline?.scrollTrigger?.kill(true); this.#timeline?.kill(); } }
export class TimeTriggerDelegate { #config; #controls; #timeline; constructor(config = {}) { this.#config = config; } build() { const c = this.#config; this.#timeline = gsap.timeline({ repeat: c.repeat ?? 0, yoyo: !!c.yoyo, repeatDelay: c.repeatDelay ?? 0, delay: typeof c.delay === "number" ? c.delay : 0, paused: !(c.autoplay ?? true) }); this.#controls = new AutonomousTimelineControls(this.#timeline); return this.#timeline; } play() { this.#controls?.play(); } pause() { this.#controls?.pause(); } seek(p) { this.#controls?.seek(p); } reverse() { this.#controls?.reverse(); } onComplete(cb) { this.#controls?.onComplete(cb); } destroy() { this.#timeline?.kill(); } }
export class ManualTriggerDelegate { #timeline; #controls; build() { this.#timeline = gsap.timeline({ paused: true }); this.#controls = new AutonomousTimelineControls(this.#timeline); return this.#timeline; } seek(p) { if (!this.#timeline) return 0; if (p === undefined) return this.#timeline.progress(); this.#controls.seek(p); } progress(p) { return this.seek(p); } play() { this.#controls?.play(); } pause() { this.#controls?.pause(); } reverse() { this.#controls?.reverse(); } onComplete(cb) { this.#controls?.onComplete(cb); } destroy() { this.#timeline?.kill(); } }
export function createTriggerDelegateRegistry(initial = [["scroll", (c) => new ScrollTriggerDelegate(c)], ["time", (c) => new TimeTriggerDelegate(c)], ["manual", (c) => new ManualTriggerDelegate(c)]]) { const registry = new Map(initial); return { get: (type) => registry.get(type), has: (type) => registry.has(type), set: (type, factory) => registry.set(type, factory), delete: (type) => registry.delete(type), entries: () => registry.entries() }; }
export const triggerDelegateRegistry = createTriggerDelegateRegistry();
export function registerTriggerDelegate(type, factory) { triggerDelegateRegistry.set(type, factory); }
