import { useCallback, useEffect, useRef, useState } from "react";
import { gsap } from "gsap";
import { engine } from "@motionpath/core/engines/Engine";
import { gsapTickerClock } from "@motionpath/core/lib/gsapTickerClock.js";
import { Spawner } from "@motionpath/core/usecases/Spawner.js";
import { BALL_COLORS, BALL_SIZE } from "./spiralConfig.js";
import { BALL_TRAVEL_SECONDS, MIN_SPAWN_PROGRESS, SPAWN_INTERVAL_MS } from "./spiralPath.js";
import { createGraphSpiralBallMotion } from "./graphSpiralMotions.js";

const WAVE_SIZE = 30; const MOTION_HOST_OPTIONS = { staggerTransition: { duration: 0.55, ease: "power2.out" }, autoplay: true };
function makeGraphBall(id) { const prefix = `graph-ball-${id}`; const motion = createGraphSpiralBallMotion({ ballSize: BALL_SIZE, ballTravelSeconds: BALL_TRAVEL_SECONDS, idPrefix: prefix }); const graph = normalizeObservationGraph(motion); const [pathConfig, entranceConfig, exitConfig] = motion.tracks; const path = engine.createTrackInstance("ball-path", { id: pathConfig.id, duration: BALL_TRAVEL_SECONDS }); const entrance = engine.createTrackInstance("ball-entrance", { id: entranceConfig.id, duration: 0.35 }); const exit = engine.createTrackInstance("ball-exit", { id: exitConfig.id, duration: 0.35 }); const tracks = new Map([[path.id, path], [entrance.id, entrance], [exit.id, exit]]); entrance.setObserved(path, (patch) => patch, { role: "output" }); exit.setObserved(path, (patch) => patch, { role: "output" }); const published = new Map(); const publisher = new GraphPublisher({ graph, tracks, publish: (trackId, patch) => published.set(trackId, patch) }); const binding = new GraphBinding({ graph, tracks, publisher }); publisher.flush(); return { id, path, entrance, exit, binding, publisher, published, status: "spawning", isClickable: false }; }
export function useGraphSpiralController({ isLoaded }) { const [ballVms, setBallVms] = useState([]); const ballsRef = useRef([]); const hostRef = useRef(null); const spawnerRef = useRef(null); const counterRef = useRef(0); const sync = useCallback(() => setBallVms(ballsRef.current.map((ball) => ({ ...ball, renderTrack: ball.status === "exiting" ? ball.exit : ball.entrance }))), []); const dispose = useCallback((ball) => { ball.binding.destroy(); engine.unmount(ball.path); engine.unmount(ball.entrance); engine.unmount(ball.exit); }, []); const remove = useCallback((ball) => { hostRef.current?.track.removeChild(ball.path.id); dispose(ball); ballsRef.current = ballsRef.current.filter((item) => item !== ball); sync(); spawnerRef.current?.notifyRemoved(1); }, [dispose, sync]); const exit = useCallback((ball) => { if (!ball || ball.status === "exiting") return; ball.status = "exiting"; ball.isClickable = false; sync(); gsap.to(ball.exit, { progress: 1, duration: 0.35, ease: "none", onComplete: () => remove(ball) }); }, [remove, sync]); const entrance = useCallback((ball) => { gsap.to(ball.entrance, { progress: 1, duration: 0.35, ease: "none", onComplete: () => { if (ball.status !== "spawning") return; ball.status = "active"; ball.isClickable = true; sync(); } }); }, [sync]); const spawn = useCallback(() => { if (!hostRef.current) return null; const id = ++counterRef.current; const ball = makeGraphBall(id); ball.color = BALL_COLORS[id % BALL_COLORS.length]; ball.onClick = () => exit(ball); ballsRef.current.push(ball); hostRef.current.track.addChild(ball.path, { stagger: SPAWN_INTERVAL_MS / 1000 }); sync(); entrance(ball); const unsubscribe = ball.path.subscribe((snapshot) => { if (snapshot.progress >= 1) { unsubscribe(); if (ball.status === "active") exit(ball); } }); return ball; }, [entrance, exit, sync]); useEffect(() => { if (!isLoaded) return undefined; const nextHost = engine.createMotionHost({ id: `graph-spiral-parent-${Date.now()}`, ...MOTION_HOST_OPTIONS }); hostRef.current = nextHost; const spawner = new Spawner({ clock: gsapTickerClock, interval: 0, maxAlive: WAVE_SIZE, waveSize: WAVE_SIZE, canSpawn: () => { const last = ballsRef.current.at(-1); return !last || last.path.progress() >= MIN_SPAWN_PROGRESS; }, factory: spawn, onComplete: () => { if (nextHost.track.childCount === 0) { spawner.resetWave(); nextHost.motion.seek(0); nextHost.motion.play(); spawner.start(); } } }); spawnerRef.current = spawner; spawner.start(); return () => { spawner.destroy(); spawnerRef.current = null; for (const ball of ballsRef.current) { nextHost.track.removeChild(ball.path.id); dispose(ball); } ballsRef.current = []; engine.unmount(nextHost.motion); hostRef.current = null; setBallVms([]); }; }, [dispose, isLoaded, spawn]); return { ballVms }; }
