import { observationEdgeEquals, observationEdgeKey } from "./observationEdge.js";
import { normalizeObservationGraph, topologicalTrackOrder } from "./normalizeObservationGraph.js";
import { toImmutableList } from "../contract/immutableValue.js";
import { ObservationStateBridge } from "./ObservationStateBridge.js";
import { trackComposeLeaf } from "./composeContext.js";

export class GraphBinding {
  #tracks; #publisher; #graph; #ownsPublisher; #observationBridge; #unsubscribers = []; #destroyed = false;
  constructor({ graph, tracks = new Map(), publisher, ownsPublisher = true, initialEdges = [] } = {}) {
    if (!publisher || typeof publisher.applyGraph !== "function") throw new TypeError("GraphBinding requires a graph-aware publisher.");
    this.#tracks = tracks instanceof Map ? new Map(tracks) : new Map(tracks); this.#publisher = publisher; this.#ownsPublisher = ownsPublisher !== false; this.#graph = this.#freeze(graph); this.#observationBridge = new ObservationStateBridge({ tracks: this.#tracks }); this.#bindObservationComposition(); if (initialEdges.length) this.#wireInitialEdges(initialEdges); this.#assertTrackGraphMatches(); this.#syncPublisher(); this.#subscribe();
  }
  get graph() { return this.#graph; } get tracks() { return new Map(this.#tracks); } getTrack(id) { return this.#tracks.get(id) ?? null; } get publisher() { return this.#publisher; } get observationState() { return this.#observationBridge?.state ?? null; } get isDestroyed() { return this.#destroyed; }
  replaceEdge(oldEdge, newEdge) { this.#assertAlive(); const observer = this.#tracks.get(oldEdge.target ?? newEdge.target); const oldSource = this.#tracks.get(oldEdge.source); const newSource = this.#tracks.get(newEdge.source); if (!observer || !oldSource || !newSource) throw new Error("replaceEdge references an unknown track."); const candidate = this.#candidateGraph((edges) => [...edges.filter((edge) => !observationEdgeEquals(edge, { ...oldEdge, target: observer.id })), this.#normalizeEdge({ ...newEdge, target: observer.id })]); const role = newEdge.role ?? oldEdge.role; const input = role === "input" ? newEdge.input ?? newEdge.target : undefined; const replaced = observer.observedEdges.filter((edge) => edge.source === oldSource && (oldEdge.role === undefined || edge.role === oldEdge.role)); this.#transaction(() => this.#changeObservation(() => this.#observationBridge.state.replaceEdge({ source: oldSource.id, target: observer.id, role: oldEdge.role }, { source: newSource.id, target: observer.id, role, input, mapFn: newEdge.mapFn }), () => observer.replaceObserved(oldSource, newSource, newEdge.mapFn, { role, target: input })), () => { const [original] = replaced; if (original) observer.replaceObserved(newSource, oldSource, original.mapFn, { role: original.role, target: original.input }); this.#refreshObservationBridge(); }, candidate); }
  addEdge(edge) { this.#assertAlive(); const observer = this.#tracks.get(edge.target); const source = this.#tracks.get(edge.source); if (!observer || !source) throw new Error("addEdge references an unknown track."); const candidate = this.#candidateGraph((edges) => [...edges, this.#normalizeEdge(edge)]); const role = edge.role ?? "output"; const input = role === "input" ? edge.input ?? edge.target : undefined; const previous = observer.observedEdges.find((existing) => existing.source === source && existing.role === role && existing.input === input); this.#transaction(() => this.#changeObservation(() => this.#observationBridge.state.addEdge({ source: source.id, target: observer.id, role, input, mapFn: edge.mapFn ?? null }), () => observer.setObserved(source, edge.mapFn ?? null, { role, target: input })), () => { if (previous) observer.setObserved(source, previous.mapFn, { role, target: input }); else observer.removeObserved(source, { role, target: input }); this.#refreshObservationBridge(); }, candidate); }
  removeEdge(edge) { this.#assertAlive(); const observer = this.#tracks.get(edge.target); const source = this.#tracks.get(edge.source); if (!observer || !source) return; const candidate = this.#candidateGraph((edges) => edges.filter((existing) => !observationEdgeEquals(existing, this.#normalizeEdge(edge)))); const removed = observer.observedEdges.filter((existing) => existing.source === source && (edge.role === undefined || existing.role === edge.role) && (edge.role !== "input" || edge.input === undefined || existing.input === edge.input)); this.#transaction(() => this.#changeObservation(() => this.#observationBridge.state.removeEdge({ source: source.id, target: observer.id, role: edge.role, input: edge.input }), () => observer.removeObserved(source, { role: edge.role, target: edge.input })), () => { for (const original of removed) observer.setObserved(source, original.mapFn, { role: original.role, target: original.input }); this.#refreshObservationBridge(); }, candidate); }
  addTrack(track, observesOrOptions = []) { this.#assertAlive(); const observes = Array.isArray(observesOrOptions) ? observesOrOptions : observesOrOptions.observes ?? []; if (!track?.id) throw new TypeError("GraphBinding.addTrack requires a Track with an id."); if (this.#tracks.has(track.id)) throw new Error(`Duplicate track id '${track.id}'.`); const candidate = this.#candidateGraph((edges) => [...edges, ...observes.map((edge) => this.#normalizeEdge({ ...edge, target: track.id }))], (nodes) => [...nodes, { id: track.id }]); const resolved = observes.map((edge) => { const source = this.#tracks.get(edge.source); if (!source) throw new Error(`Unknown source track '${edge.source}'.`); const role = edge.role ?? "output"; return { source, role, input: role === "input" ? edge.input ?? edge.target : undefined, mapFn: edge.mapFn ?? null }; }); const previousGraph = this.#graph; const undo = []; this.#tracks.set(track.id, track); this.#observationBridge.state.register(track); try { for (const { source, role, input, mapFn } of resolved) { const rollback = () => { this.#observationBridge.state.removeEdge({ source: source.id, target: track.id, role, input }); track.removeObserved(source, { role, target: input }); }; undo.push(rollback); this.#observationBridge.state.addEdge({ source: source.id, target: track.id, role, input, mapFn }); track.setObserved(source, mapFn, { role, target: input }); } this.#commit(candidate); this.#subscribeTrack(track); } catch (error) { this.#unwind(undo); this.#observationBridge.state.unregister(track.id, { detach: false }); this.#tracks.delete(track.id); this.#graph = previousGraph; this.#refreshObservationBridge(); throw error; } }
  removeTrack(id, { destroy = true } = {}) { if (this.#destroyed || !this.#tracks.has(id)) return; const track = this.#tracks.get(id); const candidate = this.#candidateGraph((edges) => edges.filter((edge) => edge.source !== id && edge.target !== id), (nodes) => nodes.filter((node) => node.id !== id)); this.#tracks.delete(id); this.#observationBridge.state.unregister(id); if (destroy && !track.isDestroyed) track.destroy?.(); this.#commit(candidate); }
  destroy() { if (this.#destroyed) return; this.#destroyed = true; for (const unsubscribe of this.#unsubscribers) unsubscribe(); this.#unsubscribers = []; this.#unbindObservationComposition(); this.#tracks = new Map(); this.#observationBridge?.destroy(); this.#observationBridge = null; const publisher = this.#publisher; this.#publisher = null; if (this.#ownsPublisher) publisher?.destroy?.(); }
  #wireInitialEdges(edges) { const undo = []; try { for (const edge of edges) { const observer = this.#tracks.get(edge.target); const source = this.#tracks.get(edge.source); if (!observer || !source) throw new Error("GraphBinding initial edge references an unknown track."); const role = edge.role ?? "output"; const input = role === "input" ? edge.input ?? edge.target : undefined; this.#observationBridge.state.addEdge({ source: source.id, target: observer.id, role, input, mapFn: edge.mapFn ?? null }); observer.setObserved(source, edge.mapFn ?? null, { role, target: input }); undo.push(() => observer.removeObserved(source, { role, target: input })); } this.#observationBridge.assertParity(); } catch (error) { for (const rollback of undo.reverse()) rollback(); this.#refreshObservationBridge(); throw error; } }
  #changeObservation(change, compatibility) { try { change(); compatibility(); } catch (error) { this.#refreshObservationBridge(); throw error; } }
  #transaction(wire, unwire, candidate) { const previousGraph = this.#graph; try { wire(); this.#commit(candidate); } catch (error) { this.#unwind([unwire]); this.#graph = previousGraph; this.#refreshObservationBridge(); throw error; } }
  #unwind(steps) { for (const step of [...steps].reverse()) { try { step(); } catch {} } }
  #normalizeEdge(edge) { const role = edge.role ?? "output"; return { source: edge.source, target: edge.target, role, input: role === "input" ? edge.input ?? edge.target : undefined }; }
  #freeze(graph) { if (!graph || graph.errors?.length) throw new Error("GraphBinding requires a valid normalized graph."); topologicalTrackOrder(graph, { strict: true }); return Object.freeze({ valid: true, nodes: toImmutableList(graph.nodes.map((node) => ({ ...node }))), edges: toImmutableList(graph.edges.map(({ source, target, role, input }) => ({ source, target, role, input }))), order: Object.freeze([...graph.order]), errors: Object.freeze([]) }); }
  #assertTrackGraphMatches() { const declaredNodes = new Set(this.#graph.nodes.map((node) => node.id)); for (const id of declaredNodes) if (!this.#tracks.has(id)) throw new Error(`GraphBinding graph declares node '${id}' with no live Track.`); for (const id of this.#tracks.keys()) if (!declaredNodes.has(id)) throw new Error(`GraphBinding holds Track '${id}' that the graph does not declare.`); const live = []; for (const track of this.#tracks.values()) for (const edge of track.observedEdges ?? []) if (edge.source && this.#tracks.get(edge.source.id) === edge.source) live.push({ source: edge.source.id, target: track.id, role: edge.role, input: edge.input }); const declared = this.#graph.edges; const key = (edge) => `${observationEdgeKey(edge.source, edge.role, edge.input)}->${edge.target}`; const declaredKeys = new Set(declared.map(key)); if (live.length !== declared.length || live.some((edge) => !declaredKeys.has(key(edge)))) throw new Error(`GraphBinding found ${live.length} live observation edges but ${declared.length} declared edges. Live Track wiring and the normalized graph must agree.`); }
  #candidateGraph(edgeMutator, nodeMutator = (nodes) => nodes) { const nodes = nodeMutator(this.#graph.nodes.map((node) => ({ id: node.id }))); const edges = edgeMutator(this.#graph.edges.map((edge) => ({ ...edge }))); const normalized = normalizeObservationGraph({ tracks: nodes.map((node) => ({ id: node.id, observes: edges.filter((edge) => edge.target === node.id).map((edge) => ({ source: edge.source, role: edge.role, target: edge.role === "input" ? edge.input : undefined })) })) }); if (!normalized.valid) throw new Error(`Rejected graph mutation: ${normalized.errors.map((error) => error.message).join("; ")}`); return normalized; }
  #commit(graph) { const frozen = this.#freeze(graph); this.#publisher.applyGraph(frozen, this.#tracks); this.#graph = frozen; this.#refreshObservationBridge(); }
  #refreshObservationBridge() { if (!this.#observationBridge) return; this.#unbindObservationComposition(); this.#observationBridge.destroy(); this.#observationBridge = new ObservationStateBridge({ tracks: this.#tracks }); this.#bindObservationComposition(); }
  #bindObservationComposition() { const bridge = this.#observationBridge; if (!bridge) return; for (const track of this.#tracks.values()) track._setObservationComposer?.((rawData, ctx) => bridge.state.compose(track.id, rawData, ctx, trackComposeLeaf)); }
  #unbindObservationComposition() { for (const track of this.#tracks.values()) track._setObservationComposer?.(null); }
  #syncPublisher() { this.#publisher.applyGraph(this.#graph, this.#tracks); }
  #subscribe() { for (const track of this.#tracks.values()) this.#subscribeTrack(track); }
  #subscribeTrack(track) { const unsubscribeLifecycle = track.onLifecycle?.((event) => { if (this.#destroyed) return; if (event.type === "destroyed") this.removeTrack(event.track.id); if (event.type === "detached") this.removeTrack(event.track.id, { destroy: false }); }); if (unsubscribeLifecycle) this.#unsubscribers.push(unsubscribeLifecycle); const unsubscribeDestroyed = track.onSourceDestroyed?.(() => {}); if (unsubscribeDestroyed) this.#unsubscribers.push(unsubscribeDestroyed); }
  #assertAlive() { if (this.#destroyed) throw new Error("GraphBinding is destroyed."); }
}
