import { gsap } from "gsap";
import React, { useCallback, useEffect, useRef } from "react";
import useMotionProject from "@motionpath/react/useMotionProject";
import useMotionSubscriber from "@motionpath/react/useMotionSubscriber";
import useMotionSubscribers from "@motionpath/react/useMotionSubscribers";
import useScrollMotion from "@motionpath/react/useScrollMotion";
import useSmoothScroll from "@motionpath/react/useSmoothScroll";
import { createTrack } from "@motionpath/core/lib/createTrack.js";
import { buildMotionPath } from "@motionpath/core/math/pathUtils.js";
import { project3DTo2D, projectPathNodes3DTo2D } from "@motionpath/core/math/projection3d.js";
import { HELIX_CONFIG, demoProject, dynamicCarouselScene, dynamicHelixScene, scrollScene } from "./demoMotions.js";
import "./DemoPage.css";
const _dummyReactRef = React;
const MOCK_CARDS = [
  { id: 1, badge: "01 / IMAGINATION", title: "Fluid Motion Engine", desc: "Harnessing the power of GSAP Pub/Sub for sub-millisecond DOM updates." },
  { id: 2, badge: "02 / ARCHITECTURE", title: "Zero Re-renders", desc: "No React component updates during animation cycles for maximum 60FPS performance." },
  { id: 3, badge: "03 / CREATIVE", title: "Bezier Interpolation", desc: "Custom paths calculated dynamically with tangent-aligned rotations." },
  { id: 4, badge: "04 / INTERACTIVE", title: "Interactive Cards", desc: "Cards respond to mouse hover with smooth glassmorphic highlighting." },
  { id: 5, badge: "05 / DESIGN", title: "Vibrant Aesthetics", desc: "Deep cosmic palettes, glassmorphism, and smooth typography curves." },
  { id: 6, badge: "06 / PERFORMANCE", title: "Scrubbed Timelines", desc: "Perfect synchronization between page scroll and complex motion paths." },
  { id: 7, badge: "07 / AWWWARDS", title: "Storytelling Layouts", desc: "Create immersive cinematic scrollytelling experiences that engage users." },
  { id: 8, badge: "08 / ANTIGRAVITY", title: "Endless Horizons", desc: "Scaling up to unlimited items on custom paths without duplicating nodes." },
];
function Rocket({ instance, offset = 0 }) { const ref = useRef(null); const transform = useCallback((rawData, composeFn) => { const progress = Math.max(0, Math.min(1, (rawData.pathProgress ?? 0) + offset)); const composed = composeFn({ ...rawData, pathProgress: progress }); return { ...composed, scale: 0.8 + progress * 0.5, opacity: 0.4 + progress * 0.6 }; }, [offset]); useMotionSubscriber(instance, "rocket-track", ref, transform); return <div ref={ref} className="element rocket">🚀</div>; }
function Cloud({ instance }) { const ref = useRef(null); const transform = useCallback((rawData, composeFn) => composeFn(rawData), []); useMotionSubscriber(instance, "cloud", ref, transform); return <div ref={ref} className="element cloud">☁️</div>; }
function useChildTrack(parentTrack, trackId, keyframes, stagger) { const [track, setTrack] = React.useState(null); useEffect(() => { if (!parentTrack) return undefined; const childTrack = createTrack({ id: trackId, keyframes }); parentTrack.addChild(childTrack, { stagger }); setTrack(childTrack); return () => parentTrack.removeChild(trackId); }, [parentTrack, trackId]); return track; }
function CarouselCard({ parentTrack, cardData, trackCfg, stagger, onRemove }) { const ref = useRef(null); const cardTrackId = `carousel-child-${cardData.id}`; const cardTrack = useChildTrack(parentTrack, cardTrackId, trackCfg.keyframes, stagger); const [exitTrack, setExitTrack] = React.useState(null); const activeTrack = exitTrack ?? cardTrack; const transform = useCallback((rawData, composeFn) => { if (exitTrack) return composeFn(rawData); const cardProgress = rawData.pathProgress ?? 0; if (cardProgress <= 0 || cardProgress >= 1) return { display: "none", opacity: 0 }; const composed = composeFn(rawData); const scale = 0.75 + Math.sin(cardProgress * Math.PI) * 0.35; const targetTilt = Math.max(-20, Math.min(20, (composed.rotation ?? 0) * 0.35)); return { ...composed, display: "flex", rotation: targetTilt, scale, rotateY: targetTilt * -0.6 }; }, [exitTrack]); useMotionSubscribers(activeTrack ? [{ track: activeTrack, transformFn: transform }] : [], ref); const handleClick = useCallback(() => { if (exitTrack || !cardTrack) return; const newExitTrack = createTrack({ id: `exit-${cardData.id}`, keyframes: { scale: { stops: [{ p: 0, v: 1 }, { p: 1, v: 0 }] }, opacity: { stops: [{ p: 0, v: 1 }, { p: 1, v: 0 }] } }, duration: 0.4 }); setExitTrack(newExitTrack); gsap.to(newExitTrack, { progress: 1, duration: 0.4, ease: "none", onComplete: () => { newExitTrack.destroy(); onRemove(cardData.id); } }); }, [exitTrack, cardTrack, cardData.id, onRemove]); if (!cardTrack) return null; return <div ref={ref} className="element carousel-card" onClick={handleClick} style={{ cursor: "pointer" }}><div className="card-badge">{cardData.badge}</div><h3>{cardData.title}</h3><p>{cardData.desc}</p><div style={{ fontSize: "10px", opacity: 0.5, marginTop: "8px" }}>(Click to Remove)</div></div>; }
function HelixCard({ parentTrack, cardData, trackCfg, stagger, trackId }) { const ref = useRef(null); const track = useChildTrack(parentTrack, trackId, trackCfg.keyframes, stagger); const transform = useCallback((rawData, composeFn) => { const cardProgress = rawData.pathProgress ?? 0; if (cardProgress <= 0 || cardProgress >= 1) return { display: "none", opacity: 0 }; const point3D = composeFn(rawData); const projected = project3DTo2D(point3D.x, point3D.y, point3D.z, HELIX_CONFIG.cx, HELIX_CONFIG.cy, HELIX_CONFIG.tiltDeg, true); const depthFactor = (point3D.z + HELIX_CONFIG.radius) / (2 * HELIX_CONFIG.radius); const scale = 0.6 + depthFactor * 0.65; const opacityBase = 0.4 + depthFactor * 0.6; const blur = Math.max(0, (1 - depthFactor) * 4); const theta = cardProgress * HELIX_CONFIG.turns * 2 * Math.PI; const rotateY = -(theta - Math.PI / 2) * (180 / Math.PI); const zIndex = Math.round(depthFactor * 100); return { display: "flex", x: projected.x, y: projected.y, xPercent: -50, yPercent: -50, scale, opacity: opacityBase, filter: `blur(${blur}px)`, zIndex, transformPerspective: 1000, rotateY }; }, []); useMotionSubscribers(track ? [{ track, transformFn: transform }] : [], ref); if (!track) return null; return <div ref={ref} className="element helix-card"><div className="card-badge">{cardData.badge}</div><h3>{cardData.title}</h3><p>{cardData.desc}</p></div>; }
function ScrollDemo({ isLoaded }) { const { refs, instance } = useScrollMotion(isLoaded ? scrollScene : null); return <section ref={refs.trigger} className="scroll-scene"><div className="scene-label"><h2>Continuous Path Animation (Scroll-Scrub)</h2><p>A rocket following a 2D bezier path curve. The clouds move linearly on their own independent track.</p></div><div ref={refs.pin} className="stage"><svg className="path-guide" width="100%" height="100%">{scrollScene.tracks.map((el) => <path key={el.id} id={`path-guide-${el.id}`} d={buildMotionPath(el.keyframes.path.points)} fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="2" strokeDasharray="8 6" />)}</svg><Cloud instance={instance} /><Rocket instance={instance} offset={0} /></div></section>; }
function CarouselDemo({ isLoaded }) { const { refs, instance } = useScrollMotion(isLoaded ? dynamicCarouselScene : null); const [cards, setCards] = React.useState(MOCK_CARDS); const parentTrack = instance?.getTrack("carousel-card-track") ?? null; const trackCfg = dynamicCarouselScene.tracks[0]; const handleRemoveCard = useCallback((cardId) => setCards((prev) => prev.filter((c) => c.id !== cardId)), []); const handleAddCard = useCallback(() => { const nextId = cards.length > 0 ? Math.max(...cards.map((c) => c.id)) + 1 : 1; const template = MOCK_CARDS[Math.floor(Math.random() * MOCK_CARDS.length)]; setCards((prev) => [...prev, { ...template, id: nextId, badge: `${String(nextId).padStart(2, "0")} / ${template.badge.split(" / ")[1] || "DYNAMIC"}` }]); }, [cards]); return <section ref={refs.trigger} className="carousel-scene"><div className="scene-label"><h2>Unlimited Carousel Scene (Scroll Stagger)</h2><p>Dynamic mock cards flowing smoothly on a single Bezier S-curve track with engine-level stagger.</p></div><div ref={refs.pin} className="carousel-stage">{cards.map((card) => <CarouselCard key={card.id} parentTrack={parentTrack} cardData={card} trackCfg={trackCfg} stagger={dynamicCarouselScene.stagger} onRemove={handleRemoveCard} />)}<svg className="path-guide" width="100%" height="100%"><path d={buildMotionPath(dynamicCarouselScene.tracks[0].keyframes.path.points)} fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="2" strokeDasharray="8 6" /></svg><button className="add-card-btn-floating" onClick={handleAddCard} title="Add Random Card">+</button></div></section>; }
function HelixDemo({ isLoaded }) { const { refs, instance } = useScrollMotion(isLoaded ? dynamicHelixScene : null); const { cx, cy, radius, height, tiltDeg } = HELIX_CONFIG; const tiltRad = (tiltDeg * Math.PI) / 180; const cylinderHeight2D = height * Math.cos(tiltRad); const projectedHelixNodes = projectPathNodes3DTo2D(dynamicHelixScene.tracks[0].keyframes.path.points, cx, cy, tiltDeg, true); const parentTrack = instance?.getTrack("helix-card-track") ?? null; const trackCfg = dynamicHelixScene.tracks[0]; const helixCards = MOCK_CARDS.slice(0, 6); return <section ref={refs.trigger} className="helix-scene"><div className="scene-label"><h2>3D Helix Card Flow (Scroll Stagger)</h2><p>Content cards flowing down a vertical spring, rotating 3D tangent to the cylinder surface</p></div><div ref={refs.pin} className="helix-stage"><svg className="path-guide" width="100%" height="100%"><defs><linearGradient id="helix-path-gradient" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stopColor="var(--accent)" stopOpacity="0.05" /><stop offset="50%" stopColor="#ff6bca" stopOpacity="0.3" /><stop offset="100%" stopColor="#ffffff" stopOpacity="0.75" /></linearGradient></defs><path id="path-guide-helix-track" d={buildMotionPath(projectedHelixNodes)} fill="none" stroke="url(#helix-path-gradient)" strokeWidth="1.5" strokeDasharray="6 4" /><line x1={cx - radius} y1={cy} x2={cx - radius} y2={cy + cylinderHeight2D} stroke="rgba(255, 255, 255, 0.04)" strokeWidth="1.5" strokeDasharray="4 4" /><line x1={cx + radius} y1={cy} x2={cx + radius} y2={cy + cylinderHeight2D} stroke="rgba(255, 255, 255, 0.04)" strokeWidth="1.5" strokeDasharray="4 4" /><line x1={cx} y1={cy} x2={cx} y2={cy + cylinderHeight2D} stroke="rgba(255, 255, 255, 0.015)" strokeWidth="1" strokeDasharray="8 6" /></svg>{helixCards.map((card, i) => <HelixCard key={card.id} parentTrack={parentTrack} cardData={card} trackCfg={trackCfg} stagger={dynamicHelixScene.stagger} trackId={`helix-child-${i}`} />)}</div></section>; }
export default function DemoPage() { const isLoaded = useMotionProject(demoProject); useSmoothScroll(); return <div className="app"><header className="header"><h1>MotionPath <span className="accent">Hooks Demo</span></h1><p className="subtitle">Zero Re-render • GSAP Pub/Sub • Direct DOM</p></header><ScrollDemo isLoaded={isLoaded} /><div className="spacer" /><CarouselDemo isLoaded={isLoaded} /><div className="spacer" /><HelixDemo isLoaded={isLoaded} /><footer className="footer"><p>Scroll back up to replay the scroll scene</p></footer></div>; }
